name: ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„-toulu
on:
  schedule:
    - cron: '4 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lululu-toulu
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
      SRC_TOULU: ${{ secrets.SRC_TOULU }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: å¼€å§‹ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: ${{ secrets.SRC_TOULU }}
          source_branch: "master"
          destination_branch: "toulu"
          github_token: ${{ secrets.PAT }}